version: '3.3'

services:
  jenkins: 
    build: 
      context: .
    ports: 
      - 8001:8080
    volumes:
      - jenkins_home_summit:/var/jenkins_home
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf
volumes:
  jenkins_home_summit:
